application: bjwebapp
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: sand.gif
  upload: favicon\.ico

- url: /d
  static_dir: direct

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
